const data = {
  products: [
    {
      _id: 1,
      name: 'Pique Polo',
      image: '/images/p1.jpg', 
      price: 120,
      brand: 'Pique',
      rating: 4.5,
      newReviews: 10,
      description: 'high quality products',
    },
    {
      _id: 2,
      name: 'Addidas',
      image: '/images/p2.jpg', 
      price: 100,
      brand: 'Pique',
      rating: 4.0,
      newReviews: 10,
      description: 'high quality products',
    },
    {
      _id: 3,
      name: 'lous vulton',
      image: '/images/p5.jpg', 
      price: 120,
      brand: 'Pique',
      rating: 4.5,
      newReviews: 10,
      description: 'high quality products',
    },
    {
      _id: 4,
      name: 'Dior',
      image: '/images/p3.jpg', 
      price: 120,
      brand: 'Pique',
      rating: 4.5,
      newReviews: 10,
      description: 'high quality products',
    },
    {
      _id: 5,
      name: 'Prada',
      image: '/images/p4.jpg', 
      price: 120,
      brand: 'Pique',
      rating: 4.5,
      newReviews: 10,
      description: 'high quality products',
    },
    {
      _id: 6,
      name: 'Emperor Amani',
      image: '/images/p6.jpg', 
      price: 120,
      brand: 'Pique',
      rating: 4.5,
      newReviews: 10,
      description: 'high quality products',
    },
  ],
};

export default data;